### ISSUE TITLE
fixed_container::reflection vs boost::reflection

### ISSUE THREAD

**Issue by younesr1** [teslamotors/fixed-containers#88]
should we make `fixed_containers::reflection` be based on `boost::reflection`. boost's version requires aggregate types, whereas fixed_container's version requires constexpr default constructible. or do we not want fixed containers to depend on boost?

**Comment by alexkaratarakis** [comment]
I haven't tested pfr reflection extensively yet, but it is possible we could remove reflection altogether from fixed_containers in favor of pfr.
